Default: &defaults
  database: ygrulog.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: ygrulog_test.sqlite3
  <<: *defaults

Staging:
  database: ygrulog_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: ygrulog_production.sqlite3
  poolsize: 100
  <<: *defaults
